version: '3'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=prodigy
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  prodigy:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - '8080:8080'

volumes:
  postgres_data: